logLevel: DEBUG  # Definição do nível de log global

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
  streaming:
    address: ":1704/udp"
  mysql:
    address: ":3306"
  metrics: # Adicionado entrypoint para as métricas
    address: ":8082"
  portainer:
    address: ":9443"
  

providers:
  file:
    filename: /etc/traefik/conf/tls.yml
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: false #so abre a dash se tiver true
    network: traefik-public # Usar a rede externa `traefik-public` do stack

websecure:
  routers:
    dashboard:
      rule: "Host(`traefik.local.dev`)"
      service: api@internal
      entryPoints: ["websecure"]
      tls: {}

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    entryPoint: metrics

# Habilitando Access Logs (opcional, mas recomendado para depuração)
accessLog: {}
