services:
  #sua gestão de tráfego em ambientes de contêinerização, como Docker e Kubernetes.
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/local.dev/:/etc/traefik
    networks:
      - local-dev
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --log.level=DEBUG # em producao use ERROR
     
    labels:
       # Redirecionar HTTP para HTTPS
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web" 
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      
      # Dashboard em HTTPS com traefik.local.dev sem solicitar senha
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.local.dev`)" 
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"

  #seu gerenciador gráfico para Docker    
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"  # Porta para HTTPS
    depends_on:
      - traefik 
    networks:
      - local-dev
    labels:
       # Roteamento HTTPS para o Portainer
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.local.dev`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"  # Usar o entryPoint 'websecure' definido no traefik.yml
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.routers.portainer.tls=true"  # Certificado TLS habilitado para HTTPS

      # Edge
      - "traefik.http.routers.edge.rule=Host(`edge.local.dev`)" #Coloque o Seu Dominio do Edge Aqui
      - "traefik.http.routers.edge.entrypoints=websecure"  # Usar o entryPoint 'https' definido no traefik.yml
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      - "traefik.http.routers.edge.service=edge"
      - "traefik.http.routers.edge.tls=true"      
volumes:
  portainer_data:

networks:
  local-dev:
    external: true