logLevel: DEBUG

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  file:
    filename: /etc/traefik/tls.yml
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: true

websecure:
  routers:
    dashboard:
      rule: "Host(`traefik.local.dev`)"
      service: api@internal
      entryPoints:
        - websecure