services:
  traefik:
    image: traefik:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
      replicas: 1
      restart_policy:
        condition: on-failure

    networks:
      - web-local
      - agent_network
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    
    labels:
      # Redirecionar HTTP para HTTPS
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # Dashboard em HTTPS com traefik.local.dev sem solicitar senha
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.local.dev`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/local.dev/traefik:/etc/traefik

    logging:
      options:
        max-size: "10m"
        max-file: "3"
 
  agent:
    image: portainer/agent:2.21.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network

    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.21.5
    # command: -H tcp://tasks.agent:9001 --tlsskipverify
    
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - agent_network
      - web-local

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.portainer.rule=Host(`portainer.local.dev`)"
    - "traefik.http.routers.portainer.tls=true"
    - "traefik.http.routers.portainer.service=portainer"
    - "traefik.http.services.portainer.loadbalancer.server.port=9000"
networks:
  agent_network:
    driver: overlay
    attachable: true
  web-local:
    external: true

volumes:
  portainer_data:
