# traefik-helm-values.yaml

ports:
  web:
    port: 80
    exposedPort: 80
  websecure:
    port: 443
    exposedPort: 443
    tls:
      enabled: true
  metrics:
    port: 9100
    exposedPort: 9100
  traefik:
    port: 8080
    exposedPort: 8080

api:
  dashboard: true

providers:
  kubernetesIngress:
    enabled: true

ingressClass:
  enabled: true
  isDefaultClass: true

service:
  type: LoadBalancer

additionalArguments:
  - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  - "--providers.docker.exposedbydefault=false"
  - "--providers.docker.endpoint=unix:///var/run/docker.sock"

# Monta o socket do Docker no pod do Traefik usando extraVolumes/extraVolumeMounts
controller:
  extraVolumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
  extraVolumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
      readOnly: true

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.local.dev`)
    entryPoints:
      - websecure
    middlewares:
      - name: traefik-dashboard-auth
        namespace: default # Namespace onde o middleware foi criado
    tls:
      secretName: local-dev-tls