# traefik-helm-values.yaml

ports:
  web:
    port: 80
    exposedPort: 80
  websecure:
    port: 443
    exposedPort: 443
  metrics:
    port: 9100
    exposedPort: 9100
  traefik:
    port: 8080
    exposedPort: 8080

api:
  dashboard: true

providers:
  kubernetesIngress:
    enabled: true

ingressClass:
  enabled: true
  isDefaultClass: true

service:
  spec:
    type: LoadBalancer

deployment:
  hostNetwork: false
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0

additionalArguments:
  - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

# Docker provider removed; Traefik will use only Kubernetes providers

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.local.dev`)
    entryPoints:
      - websecure
    middlewares:
      - name: traefik-dashboard-auth
        namespace: default # Namespace onde o middleware foi criado
    tls:
      secretName: local-dev-tls