services:
  traefik:
    image: traefik:v3.0 # Versão fixada para estabilidade
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Porta do dashboard
    command: --configFile=/etc/traefik/conf/traefik.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Acesso ao Docker Socket (read-only)
      - ./config/traefik:/etc/traefik/conf # Mapeia o diretório de configuração estática
      - ./config/dynamic:/etc/traefik/dynamic_conf # Mapeia o diretório de configuração dinâmica
      - ./certs:/etc/traefik/certs_mount # Mapeia o diretório de certificados
    networks:
      - web-local
    labels:
      # Habilita o Traefik para gerenciar a si mesmo
      - "traefik.enable=true"
      # Roteador para o dashboard do Traefik em HTTPS
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.local.dev`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      # Middleware para redirecionamento global de HTTP para HTTPS
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  portainer:
    image: portainer/portainer-ce:latest # Usando a versão mais recente para ambiente de desenvolvimento                                                                 
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    networks:
      - web-local
    labels:
      - "traefik.enable=true"
      # Roteador para o Portainer
      - "traefik.http.routers.portainer.rule=Host(`portainer.local.dev`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.service=portainer"
      # Definição do serviço do Portainer
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  web-local:
    external: true

volumes:
  portainer_data:
    driver: local
