version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - portainer_data:/data
    networks:
      - traefik-proxy # Esta rede deve ser monitorada pelo Traefik no Kubernetes

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.local.dev`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.service=portainer@docker"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000" # Porta interna do Portainer

networks:
  traefik-proxy:
    external: true # Esta rede deve ser criada manualmente se não existir

volumes:
  portainer_data:
    driver: local
