apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 5Gi # Deve ser igual ou menor que a capacidade do PV
  
