apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 20Gi # Deve ser igual ou menor que a capacidade do PV
  volumeName: mysql-pv-data
