[http.middlewares]
  [http.middlewares.simpleAuth.basicAuth]
  users = [
    "webert:$2y$05$1inqJGJJHAiEI5a0cEipUeF3AcSCpCMQARUY2cBXErpSCSYcp6Fx2"
  ]

[http.middlewares.redirect-www-to-main.redirectregex]
    permanent = true
    regex = "^https?://www\\.(.+)"
    replacement = "https://${1}"

[http.routers.api]
  rule = "Host(`traefik.local.dev`)"
  entrypoints = ["websecure"]
  service = "api@internal"
  middlewares = ["simpleAuth"]
  [http.routers.api.tls]
    certResolver = "leresolver"  